somisana/ui/admin/views/dataset.py
from pathlib import Path

from flask import Blueprint, flash, redirect, render_template, request, url_for

from odp.lib.client import ODPAPIError
from odp.ui.base import api
from odp.ui.base.templates import delete_btn, create_btn, edit_btn
from somisana.const import SOMISANAScope, EntityType, ResourceType
from somisana.ui.admin.forms import DatasetForm, image_and_gif_files_allowed

bp = Blueprint(
    'dataset',
    __name__,
    static_folder=Path(__file__).parent.parent.parent / 'catalog/static',
    static_url_path='/catalog/static'
)


@bp.route('/product_datasets/<product_id>')
@api.view(SOMISANAScope.DATASET_READ)
def product_datasets(
        product_id: int
):
    all_product_datasets = api.get(f'/dataset/product_datasets/{product_id}')

    product = api.get(f'/product/{product_id}')

    return render_template(
        'dataset_index.html',
        datasets=all_product_datasets,
        product_title=product['title'],
        buttons=[
            create_btn(
                endpoint_params=dict(
                    product_id=product_id
                )
            )
        ]
    )


@bp.route('/<id>')
@api.view(SOMISANAScope.DATASET_READ)
def detail(id):
    dataset = api.get(f'/dataset/{id}')

    return render_template(
        'dataset_detail.html',
        dataset=dataset,
        entity_type=EntityType.DATASET.value,
        cover_images=dataset['cover_images'],
        data_access_urls=dataset['data_access_urls'],
        buttons=[
            edit_btn(object_id=id),
            delete_btn(object_id=id, prompt_args=(dataset['title'],))
        ]
    )


@bp.route('/new/<product_id>/', methods=['GET', 'POST'])
@api.view(SOMISANAScope.DATASET_ADMIN)
def create(
        product_id: int
):
    form = DatasetForm(request.form)

    if request.method == 'POST' and form.validate():
        try:
            new_dataset_id = api.post(
                path='/dataset/',
                data=dict(
                    product_id=product_id,
                    title=form.title.data,
                    folder_path=form.folder_path.data,
                    visualize=form.visualize.data,
                    type=form.type.data,
                    identifier=form.identifier.data,
                )
            )
            flash(f'Dataset {new_dataset_id} has been created.', category='success')
            return redirect(url_for('.detail', id=new_dataset_id))

        except ODPAPIError as e:
            if response := api.handle_error(e):
                return response

    return render_template('dataset_edit.html', form=form, product_id=product_id)


@bp.route('/<id>/edit', methods=('GET', 'POST'))
@api.view(SOMISANAScope.DATASET_ADMIN)
def edit(id):
    dataset = api.get(f'/dataset/{id}')

    if request.method == 'POST':
        form = DatasetForm(request.form)
    else:
        form = DatasetForm(data=dataset)

    if request.method == 'POST' and form.validate():
        try:
            api.put(
                path=f'/dataset/{id}',
                data=dict(
                    product_id=dataset['product_id'],
                    title=form.title.data,
                    folder_path=form.folder_path.data,
                    visualize=form.visualize.data,
                    type=form.type.data,
                    identifier=form.identifier.data,
                )
            )
            flash(f'Dataset {id} has been updated.', category='success')
            return redirect(url_for('.detail', id=id))

        except ODPAPIError as e:
            if response := api.handle_error(e):
                return response

    return render_template('dataset_edit.html', dataset=dataset, product_id=dataset['product_id'], form=form)


@bp.route('/<id>/delete', methods=('POST',))
@api.view(SOMISANAScope.DATASET_ADMIN)
def delete(id):
    api.delete(f'/dataset/{id}')
    flash(f'Dataset {id} has been deleted.', category='success')
    return redirect(url_for('.index'))

somisana/ui/admin/views/home.py
from pathlib import Path
import requests

from flask import Blueprint, redirect, render_template, request, url_for

bp = Blueprint(
    'home',
    __name__,
    static_folder=Path(__file__).parent.parent.parent / 'catalog/static',
    static_url_path='/catalog/static'
)


@bp.route('/')
def index():
    return render_template('home.html')

somisana/ui/admin/views/resource.py
from pathlib import Path

from flask import Blueprint, flash, redirect, render_template, request, url_for

from odp.lib.client import ODPAPIError
from odp.ui.base import api
from odp.ui.base.templates import delete_btn, create_btn, edit_btn
from somisana.const import SOMISANAScope, EntityType, ResourceType, ResourceReferenceType
from somisana.ui.admin.forms import ResourceForm, image_and_gif_files_allowed

bp = Blueprint(
    'resource',
    __name__,
    static_folder=Path(__file__).parent.parent.parent / 'catalog/static',
    static_url_path='/catalog/static'
)


@bp.route('/<entity_type>/<entity_id>/')
@api.view(SOMISANAScope.RESOURCE_READ)
def resources(
        entity_type: str,
        entity_id: int
):
    all_resources = api.get(f'/{entity_type}/{entity_id}/resources')

    entity = api.get(f'/{entity_type}/{entity_id}')

    return render_template(
        'resource_index.html',
        resources=all_resources,
        entity_id=entity_id,
        entity_title=entity['title'],
        buttons=[
            create_btn(
                endpoint_params=dict(
                    entity_type=entity_type,
                    entity_id=entity_id
                )
            )
        ]
    )


@bp.route('/<id>')
@api.view(SOMISANAScope.RESOURCE_READ)
def detail(id):
    resource = api.get(f'/resource/{id}')

    return render_template(
        'resource_detail.html',
        resource=resource,
        buttons=[
            edit_btn(object_id=id),
            delete_btn(
                object_id=id,
                prompt_args=(resource['reference'],),
                endpoint_params=dict(
                    resource_id=id
                )
            )
        ]
    )


@bp.route('/new/<entity_type>/<entity_id>/', methods=['GET', 'POST'])
@api.view(SOMISANAScope.RESOURCE_ADMIN)
def create(
        entity_type: str,
        entity_id: int
):
    form = ResourceForm(request.form)

    if request.method == 'GET':
        resource_type = request.args.get('resource_type')
    else:
        resource_type = form.resource_type.data

    form.file.data = request.files.get('file')
    set_form_options(form, resource_type)

    if request.method == 'POST' and form.validate():
        try:
            if form.file.data:
                new_resource_id = api.put_files(
                    path=f'/{entity_type}/{entity_id}/resource/?resource_type={form.resource_type.data}&title={form.title.data}',
                    files={'file': (form.file.data.filename, form.file.data.stream)}
                )
            else:
                new_resource_id = api.post(
                    path=f'/{entity_type}/{entity_id}/resource/',
                    data={
                        'title': form.title.data,
                        'reference': form.reference.data,
                        'resource_type': form.resource_type.data,
                    }
                )

            flash(f'Resource {new_resource_id} has been created.', category='success')
            return get_post_create_redirect(entity_type, entity_id)

        except ODPAPIError as e:
            if response := api.handle_error(e):
                return response

    return render_template('resource_edit.html', form=form, entity_type=entity_type, entity_id=entity_id)


@bp.route('<id>/edit/', methods=('GET', 'POST'))
@api.view(SOMISANAScope.RESOURCE_ADMIN)
def edit(
        id: int
):
    resource = api.get(f'/resource/{id}')

    if request.method == 'POST':
        form = ResourceForm(request.form)
        form.file.data = request.files.get('file')

        if resource['reference_type'] == ResourceReferenceType.PATH.value and form.file.data:
            form.reference.data = None

        resource_type = form.resource_type.data
    else:
        form = ResourceForm(data=resource)

        if resource['reference_type'] == ResourceReferenceType.PATH.value:
            form.reference.render_kw = {'disabled': 'disabled'}
        elif resource['reference_type'] == ResourceReferenceType.LINK.value:
            form.file.render_kw = {'disabled': 'disabled'}

        resource_type = resource['resource_type']

    set_form_options(form, resource_type)

    if request.method == 'POST' and form.validate():
        try:
            if form.file.data:
                api.put_files(
                    path=f'/resource/{id}/?resource_type={form.resource_type.data}&title={form.title.data}',
                    files={'file': (form.file.data.filename, form.file.data.stream)}
                )
            else:
                api.post(
                    path=f'/resource/{id}/',
                    data={
                        'title': form.title.data,
                        'reference': form.reference.data,
                        'resource_type': form.resource_type.data,
                    }
                )
            flash(f'Resource {id} has been updated.', category='success')
            return redirect(url_for('.detail', id=id))

        except ODPAPIError as e:
            if response := api.handle_error(e):
                return response

    return render_template('resource_edit.html', resource=resource, form=form)


def get_post_create_redirect(entity_type: str, entity_id: int):
    match entity_type:
        case EntityType.DATASET:
            return redirect(url_for('dataset.detail', id=entity_id))
        case _:
            return redirect(url_for('.resources', entity_type=entity_type, entity_id=entity_id))


@bp.route('/<resource_id>/delete', methods=('POST',))
@api.view(SOMISANAScope.RESOURCE_ADMIN)
def delete(resource_id):
    api.delete(f'/resource/{resource_id}')
    flash(f'Resource {resource_id} has been deleted.', category='success')
    return redirect(url_for('home.index'))


def set_form_options(form, resource_type):
    match resource_type:
        case ResourceType.COVER_IMAGE | ResourceType.COVER_CLIP:
            form.resource_type.choices = [
                (ResourceType.COVER_IMAGE.value, ResourceType.COVER_IMAGE.name.replace('_', ' ').title()),
                (ResourceType.COVER_CLIP.value, ResourceType.COVER_CLIP.name.replace('_', ' ').title()),
            ]
        case ResourceType.DATA_ACCESS_URL:
            del form._fields['file']
            form.resource_type.choices = [
                (ResourceType.DATA_ACCESS_URL.value, ResourceType.DATA_ACCESS_URL.name.replace('_', ' ').title())]
        case _:
            form.resource_type.choices = [(type.value, type.name.replace('_', ' ').title()) for type in ResourceType if
                                          type.value not in [ResourceType.COVER_IMAGE, ResourceType.COVER_CLIP]]

somisana/ui/admin/templates/admin.html
{% extends 'base.html' %}

{% block main %}
<main class="flex-grow-1 m-3">
    <div class="container-xl" style="max-width: 800px">
        <div class="row mb-5">
            <div class="bg-white-op rounded p-4">
                <h1>
                    {% block heading %}
                    {% endblock %}
                </h1>
                <div class="mt-5">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

somisana/ui/admin/templates/base.html
{% extends 'layout.html' %}
{% from 'lib.j2' import bootswatch_spacelab_css, jquery_js, leaflet_js, leaflet_css %}
{% from 'admin.j2' import nav_bar_items, summernote_css, summernote_js %}

{% block web_title %}
    SOMISANA
{% endblock %}

{% block favicon %}
    <link rel="icon" href="{{ url_for('static', filename='images/mims-icon-32x32.png') }}" sizes="32x32"/>
    <link rel="icon" href="{{ url_for('static', filename='images/mims-icon-192x192.png') }}" sizes="192x192"/>
{% endblock %}

{% block header %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-white shadow-sm sticky-top">
        <div class="container-fluid justify-content-center">
            <img src="{{ url_for('.static', filename='/images/saeon-logo.png') }}" height="80">
            <img src="{{ url_for('.static', filename='/images/somisana-logo.png') }}" height="80" class="px-2">
            {{ nav_bar_items( current_user ) }}
        </div>
    </nav>
{% endblock %}

{% block footer %}
    <footer class="text-white">
        <div style="background-color: #5986C6">
            <div class="d-flex flex-row-reverse py-4">
                <div class="d-flex justify-content-center" style="width: 400px">
                    SOMISANA: {{ config.SOMISANA_VERSION }}
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

{% block styles %}
    {{ super() }}
    {{ bootswatch_spacelab_css() }}
    {{ leaflet_css() }}
    {{ summernote_css() }}
    <style>
        :root {
            --bs-link-color: #3E8A93;
            --home-background-url: url( {{ url_for('.static', filename='images/maksym-zakharyak-0V39-QUxaic-unsplash.jpg') }} );
            --bs-border-radius: 0.2em;
        }
    </style>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ jquery_js() }}
    {{ leaflet_js() }}
    {{ summernote_js() }}
    <script src="{{ url_for('static', filename='scripts/catalog.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/controls.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/leaflet-providers.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('textarea').summernote({
                toolbar: [
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['font', ['strikethrough', 'superscript', 'subscript']],
                    ['insert', ['link']],
                    ['para', ['ul', 'ol', 'paragraph']],
                ]
            });
        });
    </script>
{% endblock %}

somisana/ui/admin/templates/dataset_detail.html
{% extends 'admin.html' %}
{% from 'admin.j2' import data_table %}
{% from 'content.j2' import render_info, render_buttons %}

{% block web_title %}
    SOMISANA - Dataset Detail
{% endblock %}

{% block heading %}
    Dataset Detail
{% endblock %}

{% block content %}
    {% call(prop) render_info(dataset, 'Tite', 'Folder Path', 'Identifier', 'Type', 'Visualize', 'Data Access Link(s)', 'Cover Image(s)') %}
        {% if prop == 'Tite' %}
            {{ dataset.title }}
        {% elif prop == 'Folder Path' %}
            {{ dataset.folder_path }}
        {% elif prop == 'Identifier' %}
            {{ dataset.identifier }}
        {% elif prop == 'Type' %}
            {{ dataset.type }}
        {% elif prop == 'Visualize' %}
            {{ dataset.visualize }}
        {% elif prop == 'Data Access Link(s)' %}
            {% for data_access_url in data_access_urls %}
                {{ data_access_url.title }}
                (<a href="{{ url_for('resource.detail', id=data_access_url.id) }}">
                    view/edit
                </a>)
                <br>
            {% endfor %}
            <a href="{{ url_for('resource.create', entity_type=entity_type, entity_id=dataset.id) }}?resource_type=data_access_url">
                Add Data Access Link
            </a>
        {% elif prop == 'Cover Image(s)' %}
            {% for cover_image in cover_images %}
                {{ cover_image.title }}
                (<a href="{{ url_for('resource.detail', id=cover_image.id) }}">
                    View/Edit
                </a>)
                <br>
            {% endfor %}
            <a href="{{ url_for('resource.create', entity_type=entity_type, entity_id=dataset.id) }}?resource_type=cover_image">
                Add Cover Image
            </a>
        {% endif %}
    {% endcall %}
    {{ render_buttons(buttons) }}
{% endblock %}

somisana/ui/admin/templates/dataset_edit.html
{% extends 'admin.html' %}
{% from 'forms.j2' import render_form %}

{% block web_title %}
    SOMISANA - Dataset Edit
{% endblock %}

{% block heading %}
    Dataset Edit
{% endblock %}

{% block content %}
    {% set submit_target = url_for('.edit', id=dataset.id) if dataset else url_for('.create', product_id=product_id) %}

    {% set cancel_target = url_for('.product_datasets', product_id=product_id) %}

    <div class="alert alert-dismissible alert-info">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Note!</strong>
        The Folder Path is used by the ingester to fetch the model file.
        <br>
        Where there are dates in the file path use the syntax: &lt;YYYYMMDD&gt; in whichever permutation is required.
        YYYY will be replaced by the current year, MM with the current month and DD with the current day.
        <br>
        The root of the path should be the highest level where all model files of the same type are stored.
    </div>

    {{ render_form(
        form,
        obj=dataset,
        submit_target=submit_target,
        cancel_target=cancel_target
    ) }}
{% endblock %}

somisana/ui/admin/templates/dataset_index.html
{% extends 'admin.html' %}
{% from 'admin.j2' import data_table %}
{% from 'content.j2' import render_buttons %}

{% block web_title %}
    SOMISANA - Datasets
{% endblock %}

{% block heading %}
    Datasets {% if product_title %} for: {{ product_title }} {% endif %}
{% endblock %}

{% block content %}
    {{ data_table(
        datasets,
        {'id': 'ID',
        'title': 'Title',
        'folder_path': 'Folder Path',
        'identifier': 'Identifier',
        'type': 'Type'},
        url_key='id',
        url_param='id',
        url='.detail'
    ) }}
    {{ render_buttons(buttons) }}
{% endblock %}

somisana/ui/admin/templates/home.html
{% extends 'base.html' %}

{% block web_title %}
    SOMISANA - Admin
{% endblock %}

{% block main %}
    <main class="flex-grow-1 m-3">
        <div class="container-xl" style="max-width: 800px">
            <div class="row mb-5">
                <div class="bg-white-op rounded p-4">
                    Welcome to the somisana admin portal
                </div>
            </div>
        </div>
    </main>
{% endblock %}

somisana/ui/admin/templates/product_detail.html
{% extends 'admin.html' %}
{% from 'admin.j2' import data_table %}
{% from 'content.j2' import render_info, render_buttons %}

{% block web_title %}
    SOMISANA - Product Detail
{% endblock %}

{% block heading %}
    Product Detail
{% endblock %}

{% block content %}
    {% call(prop) render_info(
        product, 'Tite', 'Description', 'DOI', 'North Bound', 'South Bound',
        'East Bound', 'West Bound', 'Horizontal Resolution',
        'Vertical Extent', 'Vertical Resolution', 'Temporal Extent', 'Temporal Resolution',
        'Variables', 'Supersedes', 'Superseded By', 'Datasets', 'Resources'
        ) %}
        {% if prop == 'Tite' %}
            {{ product.title }}
        {% elif prop == 'Description' %}
            {{ product.description | safe }}
        {% elif prop == 'DOI' %}
            {{ product.doi }}
        {% elif prop == 'North Bound' %}
            {{ product.north_bound }}
        {% elif prop == 'South Bound' %}
            {{ product.south_bound }}
        {% elif prop == 'East Bound' %}
            {{ product.east_bound }}
        {% elif prop == 'West Bound' %}
            {{ product.west_bound }}
        {% elif prop == 'Horizontal Resolution' %}
            {{ product.horizontal_resolution }}
        {% elif prop == 'Vertical Extent' %}
            {{ product.vertical_extent }}
        {% elif prop == 'Vertical Resolution' %}
            {{ product.vertical_resolution }}
        {% elif prop == 'Temporal Extent' %}
            {{ product.temporal_extent }}
        {% elif prop == 'Temporal Resolution' %}
            {{ product.temporal_resolution }}
        {% elif prop == 'Variables' %}
            {{ product.variables }}
        {% elif prop == 'Supersedes' %}
            {% if product.superseded_product_id %}
                <a href="{{ url_for('.detail', id=product.superseded_product_id) }}">
                    {{ product.superseded_product_id }}
                </a>
            {% endif %}
        {% elif prop == 'Superseded By' %}
            {% if product.superseded_by_product_id %}
                <a href="{{ url_for('.detail', id=product.superseded_by_product_id) }}">
                    {{ product.superseded_by_product_id }}
                </a>
            {% endif %}
        {% elif prop == 'Datasets' %}
            <a href="{{ url_for('dataset.product_datasets', product_id=product.id) }}">
                View/Add Datasets
            </a>
        {% elif prop == 'Resources' %}
            <a href="{{ url_for('resource.resources', entity_type=entity_type, entity_id=product.id) }}">
                View/Add Resources
            </a>
        {% endif %}
    {% endcall %}
    {{ render_buttons(buttons) }}
{% endblock %}

somisana/ui/admin/templates/product_edit.html
{% extends 'admin.html' %}
{% from 'forms.j2' import render_form %}

{% block web_title %}
    SOMISANA - Products
{% endblock %}

{% block heading %}
    Product Edit
{% endblock %}

{% block content %}
    {{ render_form(form, product, [
        'description',
        'horizontal_resolution',
        'vertical_extent',
        'vertical_resolution',
        'temporal_extent',
        'temporal_resolution',
        'superseded_product_id'
    ]) }}
{% endblock %}

somisana/ui/admin/templates/product_index.html
{% extends 'admin.html' %}
{% from 'admin.j2' import data_table %}
{% from 'content.j2' import render_buttons %}

{% block web_title %}
    SOMISANA - Products
{% endblock %}

{% block heading %}
    Products
{% endblock %}

{% block content %}
    {{ data_table(
        all_products,
        {'id': 'ID', 'title': 'Title', 'description': 'Description', 'doi': 'DOI'},
        url_key='id',
        url_param='id',
        url='.detail'
    ) }}
    {{ render_buttons(buttons) }}
{% endblock %}

somisana/ui/admin/templates/resource_detail.html
{% extends 'admin.html' %}
{% from 'admin.j2' import data_table, render_button %}
{% from 'content.j2' import render_info, render_buttons %}

{% block web_title %}
    SOMISANA - Resource Detail
{% endblock %}

{% block heading %}
    Resource Detail
{% endblock %}

{% block content %}
    {% call(prop) render_info(resource, 'Title', 'URL', 'Resource Type', 'Reference Type') %}
        {% if prop == 'Title' %}
            {{ resource.title }}
        {% elif prop == 'URL' %}
            {{ resource.reference }}
        {% elif prop == 'Resource Type' %}
            {{ resource.resource_type }}
        {% elif prop == 'Reference Type' %}
            {{ resource.reference_type }}
        {% endif %}
    {% endcall %}
    {{ render_buttons(buttons) }}
{% endblock %}

somisana/ui/admin/templates/resource_edit.html
{% extends 'admin.html' %}
{% from 'forms.j2' import render_form %}

{% block web_title %}
    SOMISANA - {{ entity_type | title }} Resource
{% endblock %}

{% block heading %}
    {{ entity_type | title }} Resource
{% endblock %}

{% block content %}
    {% set submit_target = url_for('.edit', id=resource.id) if resource else url_for('.create', entity_type=entity_type, entity_id=entity_id) %}

    {% set cancel_target = url_for('.detail', id=resource.id) if resource else url_for('.resources', entity_type=entity_type, entity_id=entity_id) %}

    {% if resource %}
        <div class="alert alert-dismissible alert-info">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <strong>Note!</strong> A resource cannot be changed from a file to a link or vice versa. In order to make
            the change you will need to delete the resource and create a new one.
        </div>
    {% endif %}

    {{ render_form(
        form,
        obj=resource,
        file_upload=true,
        submit_target=submit_target,
        cancel_target=cancel_target
    ) }}
{% endblock %}

somisana/ui/admin/templates/resource_index.html
{% extends 'admin.html' %}
{% from 'admin.j2' import data_table %}
{% from 'content.j2' import render_buttons %}

{% block web_title %}
    SOMISANA - Product Resources
{% endblock %}

{% block heading %}
    Resources for: <small class="text-body-secondary">{{ entity_title }}</small>
{% endblock %}

{% block content %}
    {{ data_table(
        resources,
        {'id': 'ID', 'reference': 'Reference', 'reference_type': 'Reference Type', 'resource_type': 'Resource Type'},
        url_key='id',
        url_param='id',
        url='.detail'
    ) }}
    {% if entity_id %}
        {{ render_buttons(buttons) }}
    {% endif %}
{% endblock %}

somisana/ui/admin/templates/simulation_index.html
{% extends 'admin.html' %}
{% from 'admin.j2' import data_table %}
{% from 'content.j2' import render_buttons %}

{% block web_title %}
    SOMISANA - Simulations
{% endblock %}

{% block heading %}
    Simulations
{% endblock %}

{% block content %}
    {{ data_table(
        all_simulations,
        {'id': 'ID',
        'title': 'Title',
        'folder_path': 'Folder Path',
        'data_access_url': 'Data Access URL'},
        url_key='id',
        url_param='id',
        url='.detail'
    ) }}
    {{ render_buttons(buttons) }}
{% endblock %}